stages:
- build
- publish

build:
  stage: build
  image: rust:alpine
  only:
  - master
  script:
  - apk add --no-cache mingw-w64-gcc gawk
  - VERSION=$(cat Cargo.toml | awk -F'"' '/version/ { print $2 }')
  - cargo install cargo-nuget
  - rustup target add x86_86-pc-windows-gnu
  - rustup target add x86_86-unknown-linux-gnu
  - cargo build --target x86_64-pc-windows-gnu --release
  - cargo build --target x86_64-unknown-linux-gnu --release
  - cargo-nuget cross --targets win-x64 linux-x64
      --win-x64-path ./target/x86_64-pc-windows-gnu/release/improc_petrsu.dll
      --linux-x64-path ./target/x86_64-unknown-linux-gnu/release/libimproc_petrsu.so
  artifacts:
    paths:
    - improc_petrsu.$VERSION.nupkg

package-nuget:
  stage: publish
  image: mcr.microsoft.com/dotnet/sdk:5.0
  dependencies:
  - build
  only:
  - master
  script:
  - dotnet nuget push improc_petrsu.$VERSION.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
