[package]
name = "improc_petrsu"
version = "0.1.0"
authors = ["Denis Karpovskiy <geext29@gmail.com>"]
edition = "2018"
description = "My university project"
license = "MIT"

[dependencies]
image = "0.22.0"
num-traits = "^0.2.8"

[lib]
crate-type = ["dylib"]
